In [2]:
import numpy as np

myarr = np.array([[3,6,37,7]],np.int64)
myarr[0,1]

6

In [3]:
myarr.shape

(1, 4)

# Array creation: Conversion from other python structure

In [4]:
listarray = np.array([[1,2,3], [2,3,4], [3,5,6]])
listarray

array([[1, 2, 3],
       [2, 3, 4],
       [3, 5, 6]])

In [5]:
listarray.dtype

dtype('int32')

In [6]:
listarray.shape

(3, 3)

In [7]:
listarray.size

9

In [8]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
lspace = np.linspace(1,5,4)
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

# Axis in numpy

In [11]:
x = [[1,2,3],[4,5,6],[7,8,9]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
ar.sum(axis=0)

array([12, 15, 18])

In [13]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [14]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [18]:
one = np.array([1,3,4,634,2])
one.argmax()
one.argshort()

AttributeError: 'numpy.ndarray' object has no attribute 'argshort'

In [17]:
one.argshort()

AttributeError: 'numpy.ndarray' object has no attribute 'argshort'

In [19]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
ar.argmin()

0

In [21]:
ar.argmax()

8

In [22]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [23]:
ar.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [25]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
ar.reshape(3,5)

ValueError: cannot reshape array of size 9 into shape (3,5)

In [32]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
ar2 = np.array([[1, 0, 3],
       [4, 7, 6],
       [7, 2, 9]])

In [34]:
ar + ar2

array([[ 2,  2,  6],
       [ 8, 12, 12],
       [14, 10, 18]])

In [35]:
ar*ar2

array([[ 1,  0,  9],
       [16, 35, 36],
       [49, 16, 81]])

In [36]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [37]:
ar.sum()

45

In [38]:
ar.min()

1

In [39]:
ar.max()

9